#
# Generated by gen_vendor.py - Qin 2 Pro proprietary files (non-ELF)
#
# Install all prebuilt blob modules
PRODUCT_PACKAGES += qin_vendor_bin_aprctl
PRODUCT_PACKAGES += qin_vendor_bin_btools
PRODUCT_PACKAGES += qin_vendor_bin_charge
PRODUCT_PACKAGES += qin_vendor_bin_connmgr
PRODUCT_PACKAGES += qin_vendor_bin_connmgr_cli
PRODUCT_PACKAGES += qin_vendor_bin_cp_diskserver
PRODUCT_PACKAGES += qin_vendor_bin_cplogctl
PRODUCT_PACKAGES += qin_vendor_bin_engpc
PRODUCT_PACKAGES += qin_vendor_bin_enhance_test
PRODUCT_PACKAGES += qin_vendor_bin_ext_data
PRODUCT_PACKAGES += qin_vendor_bin_factorytest
PRODUCT_PACKAGES += qin_vendor_bin_flush_slog_modem
PRODUCT_PACKAGES += qin_vendor_bin_gpsd
PRODUCT_PACKAGES += qin_vendor_bin_hw_android_hardware_bluetooth_1_0_service_unisoc
PRODUCT_PACKAGES += qin_vendor_bin_hw_android_hardware_bluetooth_a2dp_1_0_service_unisoc
PRODUCT_PACKAGES += qin_vendor_bin_hw_android_hardware_drm_1_1_service_widevine
PRODUCT_PACKAGES += qin_vendor_bin_hw_android_hardware_usb_1_1_service
PRODUCT_PACKAGES += qin_vendor_bin_hw_android_hardware_audio_2_0_service
PRODUCT_PACKAGES += qin_vendor_bin_hw_sprdrild
PRODUCT_PACKAGES += qin_vendor_bin_hw_vendor_sprd_hardware_aprd_1_0_service
PRODUCT_PACKAGES += qin_vendor_bin_hw_vendor_sprd_hardware_connmgr_1_0_service
PRODUCT_PACKAGES += qin_vendor_bin_hw_vendor_sprd_hardware_enhance_1_0_service
PRODUCT_PACKAGES += qin_vendor_bin_hw_vendor_sprd_hardware_face_1_0_service
PRODUCT_PACKAGES += qin_vendor_bin_hw_vendor_sprd_hardware_gnss_2_0_service
PRODUCT_PACKAGES += qin_vendor_bin_hw_vendor_sprd_hardware_log_1_0_service
PRODUCT_PACKAGES += qin_vendor_bin_hw_vendor_sprd_hardware_power_3_0_service
PRODUCT_PACKAGES += qin_vendor_bin_hw_vendor_sprd_hardware_thermal_1_0_service
PRODUCT_PACKAGES += qin_vendor_bin_init_expand
PRODUCT_PACKAGES += qin_vendor_bin_iqfeed
PRODUCT_PACKAGES += qin_vendor_bin_iwnpi
PRODUCT_PACKAGES += qin_vendor_bin_mlogservice
PRODUCT_PACKAGES += qin_vendor_bin_modem_control
PRODUCT_PACKAGES += qin_vendor_bin_modemd
PRODUCT_PACKAGES += qin_vendor_bin_newfs_msdos
PRODUCT_PACKAGES += qin_vendor_bin_otpd
PRODUCT_PACKAGES += qin_vendor_bin_phasecheckserver
PRODUCT_PACKAGES += qin_vendor_bin_power_backlight_bright
PRODUCT_PACKAGES += qin_vendor_bin_power_cpu_dvfs_dvfs_table
PRODUCT_PACKAGES += qin_vendor_bin_power_cpu_fix_freq_fix_cpu_freq
PRODUCT_PACKAGES += qin_vendor_bin_power_cpu_hotplug_cpu_hotplug
PRODUCT_PACKAGES += qin_vendor_bin_power_cpu_lit_freq_lit_cpu_freq
PRODUCT_PACKAGES += qin_vendor_bin_power_cpu_loading_cpu_loading
PRODUCT_PACKAGES += qin_vendor_bin_power_cpu_trans_table_cpu_trans_table
PRODUCT_PACKAGES += qin_vendor_bin_power_ddr_bm_tool_ddr_bm
PRODUCT_PACKAGES += qin_vendor_bin_power_ddr_bm_tool_ddr_bm_log
PRODUCT_PACKAGES += qin_vendor_bin_power_ddr_fix_freq_fix_ddr_freq
PRODUCT_PACKAGES += qin_vendor_bin_power_ddr_loading_ddr_loading
PRODUCT_PACKAGES += qin_vendor_bin_power_ddr_trans_table_ddr_trans_table
PRODUCT_PACKAGES += qin_vendor_bin_power_frame_fps_sf
PRODUCT_PACKAGES += qin_vendor_bin_power_gpu_fix_freq_fix_gpu_freq
PRODUCT_PACKAGES += qin_vendor_bin_power_gpu_loading_gpu_loading
PRODUCT_PACKAGES += qin_vendor_bin_power_gpu_trans_table_gpu_trans_table
PRODUCT_PACKAGES += qin_vendor_bin_power_interrupt_interrupt
PRODUCT_PACKAGES += qin_vendor_bin_power_loadings_tool_loading
PRODUCT_PACKAGES += qin_vendor_bin_power_paras_tool_paras
PRODUCT_PACKAGES += qin_vendor_bin_power_paras_tool_power_ctrl
PRODUCT_PACKAGES += qin_vendor_bin_power_paras_tool_power_hint
PRODUCT_PACKAGES += qin_vendor_bin_power_tops_tops
PRODUCT_PACKAGES += qin_vendor_bin_pvrdebug
PRODUCT_PACKAGES += qin_vendor_bin_pvrhtb2txt
PRODUCT_PACKAGES += qin_vendor_bin_pvrtld
PRODUCT_PACKAGES += qin_vendor_bin_refnotify
PRODUCT_PACKAGES += qin_vendor_bin_rpmbserver
PRODUCT_PACKAGES += qin_vendor_bin_rscompiler
PRODUCT_PACKAGES += qin_vendor_bin_slogmodem
PRODUCT_PACKAGES += qin_vendor_bin_sprdstorageproxyd
PRODUCT_PACKAGES += qin_vendor_bin_srtd
PRODUCT_PACKAGES += qin_vendor_bin_systemDebuggerd
PRODUCT_PACKAGES += qin_vendor_bin_thermald
PRODUCT_PACKAGES += qin_vendor_bin_tsupplicant
PRODUCT_PACKAGES += qin_vendor_bin_wifi_mac_gen
PRODUCT_PACKAGES += qin_vendor_bin_ylog_lite
PRODUCT_PACKAGES += qin_vendor_bin_ylog_lite_cli
PRODUCT_PACKAGES += qin_vendor_lib64_camera_device_3_2_impl_sprd_so
PRODUCT_PACKAGES += qin_vendor_lib64_camera_device_3_3_impl_sprd_so
PRODUCT_PACKAGES += qin_vendor_lib64_camera_device_3_4_impl_sprd_so
PRODUCT_PACKAGES += qin_vendor_lib64_egl_libEGL_POWERVR_ROGUE_so
PRODUCT_PACKAGES += qin_vendor_lib64_egl_libGLESv1_CM_POWERVR_ROGUE_so
PRODUCT_PACKAGES += qin_vendor_lib64_egl_libGLESv2_POWERVR_ROGUE_so
PRODUCT_PACKAGES += qin_vendor_lib64_hw_android_hardware_bluetooth_1_0_impl_unisoc_so
PRODUCT_PACKAGES += qin_vendor_lib64_hw_android_hardware_bluetooth_a2dp_1_0_impl_unisoc_so
PRODUCT_PACKAGES += qin_vendor_lib64_hw_android_hardware_camera_provider_2_4_impl_sprd_so
PRODUCT_PACKAGES += qin_vendor_lib64_hw_android_hardware_graphics_composer_2_1_impl_so
PRODUCT_PACKAGES += qin_vendor_lib64_hw_android_hardware_health_1_0_impl_so
PRODUCT_PACKAGES += qin_vendor_lib64_hw_dpu_sp9863a_so
PRODUCT_PACKAGES += qin_vendor_lib64_hw_enhance_sp9863a_so
PRODUCT_PACKAGES += qin_vendor_lib64_hw_gatekeeper_default_so
PRODUCT_PACKAGES += qin_vendor_lib64_hw_gps_default_so
PRODUCT_PACKAGES += qin_vendor_lib64_hw_gralloc_sp9863a_so
PRODUCT_PACKAGES += qin_vendor_lib64_hw_gsp_sp9863a_so
PRODUCT_PACKAGES += qin_vendor_lib64_hw_keystore_sp9863a_so
PRODUCT_PACKAGES += qin_vendor_lib64_hw_keystore_sprdtrusty_so
PRODUCT_PACKAGES += qin_vendor_lib64_hw_lights_sp9863a_so
PRODUCT_PACKAGES += qin_vendor_lib64_hw_memtrack_sp9863a_so
PRODUCT_PACKAGES += qin_vendor_lib64_hw_sensors_sp9863a_so
PRODUCT_PACKAGES += qin_vendor_lib64_hw_vendor_sprd_hardware_aprd_1_0_impl_so
PRODUCT_PACKAGES += qin_vendor_lib64_hw_vendor_sprd_hardware_connmgr_1_0_impl_so
PRODUCT_PACKAGES += qin_vendor_lib64_hw_vendor_sprd_hardware_enhance_1_0_impl_so
PRODUCT_PACKAGES += qin_vendor_lib64_hw_vendor_sprd_hardware_gnss_2_0_impl_so
PRODUCT_PACKAGES += qin_vendor_lib64_hw_vendor_sprd_hardware_log_1_0_impl_so
PRODUCT_PACKAGES += qin_vendor_lib64_hw_vendor_sprd_hardware_power_3_0_impl_so
PRODUCT_PACKAGES += qin_vendor_lib64_hw_vendor_sprd_hardware_thermal_1_0_impl_so
PRODUCT_PACKAGES += qin_vendor_lib64_libBokeh2Frames_so
PRODUCT_PACKAGES += qin_vendor_lib64_libDivRIL_so
PRODUCT_PACKAGES += qin_vendor_lib64_libIMGegl_so
PRODUCT_PACKAGES += qin_vendor_lib64_libPVRRS_sha1_so
PRODUCT_PACKAGES += qin_vendor_lib64_libPVRRS_so
PRODUCT_PACKAGES += qin_vendor_lib64_libPVRScopeServices_so
PRODUCT_PACKAGES += qin_vendor_lib64_libSegLite_so
PRODUCT_PACKAGES += qin_vendor_lib64_libSprdImageFilter_so
PRODUCT_PACKAGES += qin_vendor_lib64_libSprdPdAlgo_so
PRODUCT_PACKAGES += qin_vendor_lib64_libXMPCore_so
PRODUCT_PACKAGES += qin_vendor_lib64_libXMPFiles_so
PRODUCT_PACKAGES += qin_vendor_lib64_lib_remote_simlock_so
PRODUCT_PACKAGES += qin_vendor_lib64_libae_so
PRODUCT_PACKAGES += qin_vendor_lib64_libatci_so
PRODUCT_PACKAGES += qin_vendor_lib64_libatm_so
PRODUCT_PACKAGES += qin_vendor_lib64_libaudionpi_so
PRODUCT_PACKAGES += qin_vendor_lib64_libaudioparamteser_so
PRODUCT_PACKAGES += qin_vendor_lib64_libawb1_so
PRODUCT_PACKAGES += qin_vendor_lib64_libbokeh_depth_so
PRODUCT_PACKAGES += qin_vendor_lib64_libbokeh_gaussian_cap_so
PRODUCT_PACKAGES += qin_vendor_lib64_libbokeh_gaussian_so
PRODUCT_PACKAGES += qin_vendor_lib64_libbt_sprd_suite_so
PRODUCT_PACKAGES += qin_vendor_lib64_libbt_vendor_so
PRODUCT_PACKAGES += qin_vendor_lib64_libcam_otp_parser_so
PRODUCT_PACKAGES += qin_vendor_lib64_libcambr_so
PRODUCT_PACKAGES += qin_vendor_lib64_libcamcommon_so
PRODUCT_PACKAGES += qin_vendor_lib64_libcamdrv_so
PRODUCT_PACKAGES += qin_vendor_lib64_libcamfb_so
PRODUCT_PACKAGES += qin_vendor_lib64_libcamoem_so
PRODUCT_PACKAGES += qin_vendor_lib64_libcampm_so
PRODUCT_PACKAGES += qin_vendor_lib64_libcamrt_so
PRODUCT_PACKAGES += qin_vendor_lib64_libcamsensor_so
PRODUCT_PACKAGES += qin_vendor_lib64_libcreatesurface_so
PRODUCT_PACKAGES += qin_vendor_lib64_libdeflicker_so
PRODUCT_PACKAGES += qin_vendor_lib64_libefuse_so
PRODUCT_PACKAGES += qin_vendor_lib64_libeng_tok_so
PRODUCT_PACKAGES += qin_vendor_lib64_libfaceid_ca_so
PRODUCT_PACKAGES += qin_vendor_lib64_libfacepose_so
PRODUCT_PACKAGES += qin_vendor_lib64_libfactorylib_so
PRODUCT_PACKAGES += qin_vendor_lib64_libflash_so
PRODUCT_PACKAGES += qin_vendor_lib64_libfprint_x64_so
PRODUCT_PACKAGES += qin_vendor_lib64_libglslcompiler_so
PRODUCT_PACKAGES += qin_vendor_lib64_libhdr_so
PRODUCT_PACKAGES += qin_vendor_lib64_libispalg_so
PRODUCT_PACKAGES += qin_vendor_lib64_libiwnpi_so
PRODUCT_PACKAGES += qin_vendor_lib64_libjpeg_hw_sprd_so
PRODUCT_PACKAGES += qin_vendor_lib64_libkernelbootcp_trusty_so
PRODUCT_PACKAGES += qin_vendor_lib64_libtrusty_so
PRODUCT_PACKAGES += qin_vendor_lib_libtrusty_so
PRODUCT_PACKAGES += qin_vendor_lib64_liblcsagent_so
PRODUCT_PACKAGES += qin_vendor_lib64_liblcscp_so
PRODUCT_PACKAGES += qin_vendor_lib64_liblcsmgt_so
PRODUCT_PACKAGES += qin_vendor_lib64_liblcswbxml2_so
PRODUCT_PACKAGES += qin_vendor_lib64_libcld80211_so
PRODUCT_PACKAGES += qin_vendor_lib64_liblowi_wifihal_so
PRODUCT_PACKAGES += qin_vendor_lib64_liblsc_so
PRODUCT_PACKAGES += qin_vendor_lib64_liblte_so
PRODUCT_PACKAGES += qin_vendor_lib64_libmapuser_so
PRODUCT_PACKAGES += qin_vendor_lib64_libmemion_so
PRODUCT_PACKAGES += qin_vendor_lib64_libnvexchange_so
PRODUCT_PACKAGES += qin_vendor_lib64_libomx_avcdec_hw_sprd_so
PRODUCT_PACKAGES += qin_vendor_lib64_libomx_avcdec_sw_sprd_so
PRODUCT_PACKAGES += qin_vendor_lib64_libomx_avcdec_vt_sprd_so
PRODUCT_PACKAGES += qin_vendor_lib64_libomx_avcenc_hw_sprd_so
PRODUCT_PACKAGES += qin_vendor_lib64_libomx_hevcdec_hw_sprd_so
PRODUCT_PACKAGES += qin_vendor_lib64_libomx_hevcenc_hw_sprd_so
PRODUCT_PACKAGES += qin_vendor_lib64_libomx_m4vh263dec_hw_sprd_so
PRODUCT_PACKAGES += qin_vendor_lib64_libomx_m4vh263dec_sw_sprd_so
PRODUCT_PACKAGES += qin_vendor_lib64_libomx_m4vh263enc_sw_sprd_so
PRODUCT_PACKAGES += qin_vendor_lib64_libomx_mp3enc_sprd_so
PRODUCT_PACKAGES += qin_vendor_lib64_libomx_vp9dec_hw_sprd_so
PRODUCT_PACKAGES += qin_vendor_lib64_libomx_vpxdec_hw_sprd_so
PRODUCT_PACKAGES += qin_vendor_lib64_libomx_vpxenc_hw_sprd_so
PRODUCT_PACKAGES += qin_vendor_lib64_libpowerhal_cli_so
PRODUCT_PACKAGES += qin_vendor_lib64_libpvrANDROID_WSEGL_so
PRODUCT_PACKAGES += qin_vendor_lib64_libril_threads_so
PRODUCT_PACKAGES += qin_vendor_lib64_librilsprd_single_so
PRODUCT_PACKAGES += qin_vendor_lib64_librilsprd_so
PRODUCT_PACKAGES += qin_vendor_lib64_librpmbclient_so
PRODUCT_PACKAGES += qin_vendor_lib64_libsensorlistcfg_so
PRODUCT_PACKAGES += qin_vendor_lib64_libsensornpi_so
PRODUCT_PACKAGES += qin_vendor_lib64_libsensorsdrvcfg_so
PRODUCT_PACKAGES += qin_vendor_lib64_libspafv1_so
PRODUCT_PACKAGES += qin_vendor_lib64_libspcaftrigger_so
PRODUCT_PACKAGES += qin_vendor_lib64_libsprd_omx_core_so
PRODUCT_PACKAGES += qin_vendor_lib64_libsprd_ril_single_so
PRODUCT_PACKAGES += qin_vendor_lib64_libsprd_ril_so
PRODUCT_PACKAGES += qin_vendor_lib64_libsprdaic_so
PRODUCT_PACKAGES += qin_vendor_lib64_libsprdaudiohal_4_0_so
PRODUCT_PACKAGES += qin_vendor_lib64_libsprdaudiohal_deathhandler_so
PRODUCT_PACKAGES += qin_vendor_lib64_libsprdaudiohal_so
PRODUCT_PACKAGES += qin_vendor_lib64_libsprdbokeh_so
PRODUCT_PACKAGES += qin_vendor_lib64_libsprdcnr_so
PRODUCT_PACKAGES += qin_vendor_lib64_libsprddepth_so
PRODUCT_PACKAGES += qin_vendor_lib64_libsprdfa_so
PRODUCT_PACKAGES += qin_vendor_lib64_libsprdfacebeauty_so
PRODUCT_PACKAGES += qin_vendor_lib64_libsprdfaceid_so
PRODUCT_PACKAGES += qin_vendor_lib64_libsprdfar_so
PRODUCT_PACKAGES += qin_vendor_lib64_libsprdfd_so
PRODUCT_PACKAGES += qin_vendor_lib64_libsprdhdr_so
PRODUCT_PACKAGES += qin_vendor_lib64_libsprdlsc_so
PRODUCT_PACKAGES += qin_vendor_lib64_libsprdscenedetect_so
PRODUCT_PACKAGES += qin_vendor_lib64_libsprdswisp_so
PRODUCT_PACKAGES += qin_vendor_lib64_libsrv_um_so
PRODUCT_PACKAGES += qin_vendor_lib64_libstagefright_soft_imaadpcmdec_so
PRODUCT_PACKAGES += qin_vendor_lib64_libstagefright_soft_mjpgdec_so
PRODUCT_PACKAGES += qin_vendor_lib64_libstagefright_sprd_deintl_so
PRODUCT_PACKAGES += qin_vendor_lib64_libstagefright_sprd_h264dec_so
PRODUCT_PACKAGES += qin_vendor_lib64_libstagefright_sprd_h264enc_so
PRODUCT_PACKAGES += qin_vendor_lib64_libstagefright_sprd_h265dec_so
PRODUCT_PACKAGES += qin_vendor_lib64_libstagefright_sprd_h265enc_so
PRODUCT_PACKAGES += qin_vendor_lib64_libstagefright_sprd_mp3dec_so
PRODUCT_PACKAGES += qin_vendor_lib64_libstagefright_sprd_mp3enc_so
PRODUCT_PACKAGES += qin_vendor_lib64_libstagefright_sprd_mpeg4dec_so
PRODUCT_PACKAGES += qin_vendor_lib64_libstagefright_sprd_mpeg4enc_so
PRODUCT_PACKAGES += qin_vendor_lib64_libstagefright_sprd_vp9dec_so
PRODUCT_PACKAGES += qin_vendor_lib64_libstagefright_sprd_vpxdec_so
PRODUCT_PACKAGES += qin_vendor_lib64_libstagefrighthw_so
PRODUCT_PACKAGES += qin_vendor_lib64_libsupl_so
PRODUCT_PACKAGES += qin_vendor_lib64_libsutu_display_so
PRODUCT_PACKAGES += qin_vendor_lib64_libteeproduction_so
PRODUCT_PACKAGES += qin_vendor_lib64_libtqvalidate_so
PRODUCT_PACKAGES += qin_vendor_lib64_libusc_so
PRODUCT_PACKAGES += qin_vendor_lib64_libvbeffect_so
PRODUCT_PACKAGES += qin_vendor_lib64_libwebrtc_audio_preprocessing_so
PRODUCT_PACKAGES += qin_vendor_lib64_libyuv420_scaler_so
PRODUCT_PACKAGES += qin_vendor_lib64_npidevice_PQTune_sp9863a_so
PRODUCT_PACKAGES += qin_vendor_lib64_npidevice_libFactoryRadioTest_so
PRODUCT_PACKAGES += qin_vendor_lib64_npidevice_libcheckkeybox_so
PRODUCT_PACKAGES += qin_vendor_lib64_npidevice_libgetuid_so
PRODUCT_PACKAGES += qin_vendor_lib64_power_sprd_so
PRODUCT_PACKAGES += qin_vendor_lib64_production_libpubefuseapi_so
PRODUCT_PACKAGES += qin_vendor_lib64_vendor_sprd_hardware_aprd_1_0_so
PRODUCT_PACKAGES += qin_vendor_lib64_vendor_sprd_hardware_connmgr_1_0_so
PRODUCT_PACKAGES += qin_vendor_lib64_vendor_sprd_hardware_enhance_1_0_so
PRODUCT_PACKAGES += qin_vendor_lib64_vendor_sprd_hardware_face_1_0_so
PRODUCT_PACKAGES += qin_vendor_lib64_vendor_sprd_hardware_gnss_2_0_so
PRODUCT_PACKAGES += qin_vendor_lib64_vendor_sprd_hardware_log_1_0_so
PRODUCT_PACKAGES += qin_vendor_lib64_vendor_sprd_hardware_power_3_0_so
PRODUCT_PACKAGES += qin_vendor_lib64_vendor_sprd_hardware_radio_1_0_so
PRODUCT_PACKAGES += qin_vendor_lib64_vendor_sprd_hardware_radio_flavor_1_0_so
PRODUCT_PACKAGES += qin_vendor_lib64_vendor_sprd_hardware_thermal_1_0_so
PRODUCT_PACKAGES += qin_vendor_lib64_vendor_sprd_hardware_wifi_hostapd_1_0_so
PRODUCT_PACKAGES += qin_vendor_lib64_vendor_sprd_hardware_wifi_supplicant_1_1_so
PRODUCT_PACKAGES += qin_vendor_lib_camera_device_3_2_impl_sprd_so
PRODUCT_PACKAGES += qin_vendor_lib_camera_device_3_3_impl_sprd_so
PRODUCT_PACKAGES += qin_vendor_lib_camera_device_3_4_impl_sprd_so
PRODUCT_PACKAGES += qin_vendor_lib_egl_libEGL_POWERVR_ROGUE_so
PRODUCT_PACKAGES += qin_vendor_lib_egl_libGLESv1_CM_POWERVR_ROGUE_so
PRODUCT_PACKAGES += qin_vendor_lib_egl_libGLESv2_POWERVR_ROGUE_so
PRODUCT_PACKAGES += qin_vendor_lib_hw_android_hardware_bluetooth_1_0_impl_unisoc_so
PRODUCT_PACKAGES += qin_vendor_lib_hw_android_hardware_bluetooth_a2dp_1_0_impl_unisoc_so
PRODUCT_PACKAGES += qin_vendor_lib_hw_android_hardware_camera_provider_2_4_impl_sprd_so
PRODUCT_PACKAGES += qin_vendor_lib_hw_android_hardware_graphics_composer_2_1_impl_so
PRODUCT_PACKAGES += qin_vendor_lib_hw_android_hardware_health_1_0_impl_so
PRODUCT_PACKAGES += qin_vendor_lib_hw_audio_primary_sp9863a_so
PRODUCT_PACKAGES += qin_vendor_lib_hw_dpu_sp9863a_so
PRODUCT_PACKAGES += qin_vendor_lib_hw_enhance_sp9863a_so
PRODUCT_PACKAGES += qin_vendor_lib_hw_gatekeeper_default_so
PRODUCT_PACKAGES += qin_vendor_lib_hw_gps_default_so
PRODUCT_PACKAGES += qin_vendor_lib_hw_gralloc_sp9863a_so
PRODUCT_PACKAGES += qin_vendor_lib_hw_gsp_sp9863a_so
PRODUCT_PACKAGES += qin_vendor_lib_hw_keystore_sp9863a_so
PRODUCT_PACKAGES += qin_vendor_lib_hw_keystore_sprdtrusty_so
PRODUCT_PACKAGES += qin_vendor_lib_hw_lights_sp9863a_so
PRODUCT_PACKAGES += qin_vendor_lib_hw_memtrack_sp9863a_so
PRODUCT_PACKAGES += qin_vendor_lib_hw_sensors_sp9863a_so
PRODUCT_PACKAGES += qin_vendor_lib_hw_vendor_sprd_hardware_aprd_1_0_impl_so
PRODUCT_PACKAGES += qin_vendor_lib_hw_vendor_sprd_hardware_connmgr_1_0_impl_so
PRODUCT_PACKAGES += qin_vendor_lib_hw_vendor_sprd_hardware_enhance_1_0_impl_so
PRODUCT_PACKAGES += qin_vendor_lib_hw_vendor_sprd_hardware_gnss_2_0_impl_so
PRODUCT_PACKAGES += qin_vendor_lib_hw_vendor_sprd_hardware_log_1_0_impl_so
PRODUCT_PACKAGES += qin_vendor_lib_hw_vendor_sprd_hardware_power_3_0_impl_so
PRODUCT_PACKAGES += qin_vendor_lib_hw_vendor_sprd_hardware_thermal_1_0_impl_so
PRODUCT_PACKAGES += qin_vendor_lib_libAudioCustomMmi_so
PRODUCT_PACKAGES += qin_vendor_lib_libBokeh2Frames_so
PRODUCT_PACKAGES += qin_vendor_lib_libDivRIL_so
PRODUCT_PACKAGES += qin_vendor_lib_libFMHalSource_so
PRODUCT_PACKAGES += qin_vendor_lib_libIMGegl_so
PRODUCT_PACKAGES += qin_vendor_lib_libPVRRS_sha1_so
PRODUCT_PACKAGES += qin_vendor_lib_libPVRRS_so
PRODUCT_PACKAGES += qin_vendor_lib_libPVRScopeServices_so
PRODUCT_PACKAGES += qin_vendor_lib_libSegLite_so
PRODUCT_PACKAGES += qin_vendor_lib_libSprdImageFilter_so
PRODUCT_PACKAGES += qin_vendor_lib_libSprdPdAlgo_so
PRODUCT_PACKAGES += qin_vendor_lib_libXMPCore_so
PRODUCT_PACKAGES += qin_vendor_lib_libXMPFiles_so
PRODUCT_PACKAGES += qin_vendor_lib_lib_factorytest_ft2_so
PRODUCT_PACKAGES += qin_vendor_lib_lib_remote_simlock_so
PRODUCT_PACKAGES += qin_vendor_lib_libae_so
PRODUCT_PACKAGES += qin_vendor_lib_libatci_so
PRODUCT_PACKAGES += qin_vendor_lib_libatm_so
PRODUCT_PACKAGES += qin_vendor_lib_libaudiomiscctl_so
PRODUCT_PACKAGES += qin_vendor_lib_libaudionpi_so
PRODUCT_PACKAGES += qin_vendor_lib_libaudioparamteser_so
PRODUCT_PACKAGES += qin_vendor_lib_libawb1_so
PRODUCT_PACKAGES += qin_vendor_lib_libbm_so
PRODUCT_PACKAGES += qin_vendor_lib_libbokeh_depth_so
PRODUCT_PACKAGES += qin_vendor_lib_libbokeh_gaussian_cap_so
PRODUCT_PACKAGES += qin_vendor_lib_libbokeh_gaussian_so
PRODUCT_PACKAGES += qin_vendor_lib_libbqbbt_so
PRODUCT_PACKAGES += qin_vendor_lib_libbt_sprd_suite_so
PRODUCT_PACKAGES += qin_vendor_lib_libbt_vendor_so
PRODUCT_PACKAGES += qin_vendor_lib_libcam_otp_parser_so
PRODUCT_PACKAGES += qin_vendor_lib_libcambr_so
PRODUCT_PACKAGES += qin_vendor_lib_libcamcommon_so
PRODUCT_PACKAGES += qin_vendor_lib_libcamdrv_so
PRODUCT_PACKAGES += qin_vendor_lib_libcamfb_so
PRODUCT_PACKAGES += qin_vendor_lib_libcamoem_so
PRODUCT_PACKAGES += qin_vendor_lib_libcampm_so
PRODUCT_PACKAGES += qin_vendor_lib_libcamrt_so
PRODUCT_PACKAGES += qin_vendor_lib_libcamsensor_so
PRODUCT_PACKAGES += qin_vendor_lib_libcompresssimu_so
PRODUCT_PACKAGES += qin_vendor_lib_libcreatesurface_so
PRODUCT_PACKAGES += qin_vendor_lib_libdeflicker_so
PRODUCT_PACKAGES += qin_vendor_lib_libdumpdata_so
PRODUCT_PACKAGES += qin_vendor_lib_libefuse_so
PRODUCT_PACKAGES += qin_vendor_lib_libeng_tok_so
PRODUCT_PACKAGES += qin_vendor_lib_libengbt_so
PRODUCT_PACKAGES += qin_vendor_lib_libengfm_so
PRODUCT_PACKAGES += qin_vendor_lib_libfaceid_ca_so
PRODUCT_PACKAGES += qin_vendor_lib_libfacepose_so
PRODUCT_PACKAGES += qin_vendor_lib_libfactorylib_so
PRODUCT_PACKAGES += qin_vendor_lib_libflash_so
PRODUCT_PACKAGES += qin_vendor_lib_libfmjni_so
PRODUCT_PACKAGES += qin_vendor_lib_libfprint_x32_so
PRODUCT_PACKAGES += qin_vendor_lib_libglslcompiler_so
PRODUCT_PACKAGES += qin_vendor_lib_libhdr_so
PRODUCT_PACKAGES += qin_vendor_lib_libispalg_so
PRODUCT_PACKAGES += qin_vendor_lib_libiwnpi_so
PRODUCT_PACKAGES += qin_vendor_lib_libjpeg_hw_sprd_so
PRODUCT_PACKAGES += qin_vendor_lib_liblcsagent_so
PRODUCT_PACKAGES += qin_vendor_lib_liblcscp_so
PRODUCT_PACKAGES += qin_vendor_lib_liblcsmgt_so
PRODUCT_PACKAGES += qin_vendor_lib_liblcswbxml2_so
PRODUCT_PACKAGES += qin_vendor_lib_libcld80211_so
PRODUCT_PACKAGES += qin_vendor_lib_liblowi_wifihal_so
PRODUCT_PACKAGES += qin_vendor_lib_liblsc_so
PRODUCT_PACKAGES += qin_vendor_lib_liblte_so
PRODUCT_PACKAGES += qin_vendor_lib_libmapuser_so
PRODUCT_PACKAGES += qin_vendor_lib_libmemion_so
PRODUCT_PACKAGES += qin_vendor_lib_libnpi_rtc_so
PRODUCT_PACKAGES += qin_vendor_lib_libnvexchange_so
PRODUCT_PACKAGES += qin_vendor_lib_libomx_avcdec_hw_sprd_so
PRODUCT_PACKAGES += qin_vendor_lib_libomx_avcdec_sw_sprd_so
PRODUCT_PACKAGES += qin_vendor_lib_libomx_avcdec_vt_sprd_so
PRODUCT_PACKAGES += qin_vendor_lib_libomx_avcenc_hw_sprd_so
PRODUCT_PACKAGES += qin_vendor_lib_libomx_hevcdec_hw_sprd_so
PRODUCT_PACKAGES += qin_vendor_lib_libomx_hevcenc_hw_sprd_so
PRODUCT_PACKAGES += qin_vendor_lib_libomx_m4vh263dec_hw_sprd_so
PRODUCT_PACKAGES += qin_vendor_lib_libomx_m4vh263dec_sw_sprd_so
PRODUCT_PACKAGES += qin_vendor_lib_libomx_m4vh263enc_sw_sprd_so
PRODUCT_PACKAGES += qin_vendor_lib_libomx_mp3dec_sprd_so
PRODUCT_PACKAGES += qin_vendor_lib_libomx_mp3enc_sprd_so
PRODUCT_PACKAGES += qin_vendor_lib_libomx_vp9dec_hw_sprd_so
PRODUCT_PACKAGES += qin_vendor_lib_libomx_vpxdec_hw_sprd_so
PRODUCT_PACKAGES += qin_vendor_lib_libomx_vpxenc_hw_sprd_so
PRODUCT_PACKAGES += qin_vendor_lib_libpowerhal_cli_so
PRODUCT_PACKAGES += qin_vendor_lib_libpvrANDROID_WSEGL_so
PRODUCT_PACKAGES += qin_vendor_lib_libresample48kto44k_so
PRODUCT_PACKAGES += qin_vendor_lib_libril_threads_so
PRODUCT_PACKAGES += qin_vendor_lib_librilsprd_single_so
PRODUCT_PACKAGES += qin_vendor_lib_librilsprd_so
PRODUCT_PACKAGES += qin_vendor_lib_librpmbclient_so
PRODUCT_PACKAGES += qin_vendor_lib_libsensorlistcfg_so
PRODUCT_PACKAGES += qin_vendor_lib_libsensornpi_so
PRODUCT_PACKAGES += qin_vendor_lib_libsensorsdrvcfg_so
PRODUCT_PACKAGES += qin_vendor_lib_libsmartamp_so
PRODUCT_PACKAGES += qin_vendor_lib_libspafv1_so
PRODUCT_PACKAGES += qin_vendor_lib_libspcaftrigger_so
PRODUCT_PACKAGES += qin_vendor_lib_libsprd_omx_core_so
PRODUCT_PACKAGES += qin_vendor_lib_libsprd_ril_single_so
PRODUCT_PACKAGES += qin_vendor_lib_libsprd_ril_so
PRODUCT_PACKAGES += qin_vendor_lib_libsprdaic_so
PRODUCT_PACKAGES += qin_vendor_lib_libsprdaudiohal_4_0_so
PRODUCT_PACKAGES += qin_vendor_lib_libsprdaudiohal_deathhandler_so
PRODUCT_PACKAGES += qin_vendor_lib_libsprdaudiohal_so
PRODUCT_PACKAGES += qin_vendor_lib_libsprdbokeh_so
PRODUCT_PACKAGES += qin_vendor_lib_libsprdcnr_so
PRODUCT_PACKAGES += qin_vendor_lib_libsprddepth_so
PRODUCT_PACKAGES += qin_vendor_lib_libsprdfa_so
PRODUCT_PACKAGES += qin_vendor_lib_libsprdfacebeauty_so
PRODUCT_PACKAGES += qin_vendor_lib_libsprdfaceid_so
PRODUCT_PACKAGES += qin_vendor_lib_libsprdfar_so
PRODUCT_PACKAGES += qin_vendor_lib_libsprdfd_so
PRODUCT_PACKAGES += qin_vendor_lib_libsprdhdr_so
PRODUCT_PACKAGES += qin_vendor_lib_libsprdlsc_so
PRODUCT_PACKAGES += qin_vendor_lib_libsprdscenedetect_so
PRODUCT_PACKAGES += qin_vendor_lib_libsprdswisp_so
PRODUCT_PACKAGES += qin_vendor_lib_libsrv_um_so
PRODUCT_PACKAGES += qin_vendor_lib_libstagefright_soft_imaadpcmdec_so
PRODUCT_PACKAGES += qin_vendor_lib_libstagefright_soft_mjpgdec_so
PRODUCT_PACKAGES += qin_vendor_lib_libstagefright_sprd_deintl_so
PRODUCT_PACKAGES += qin_vendor_lib_libstagefright_sprd_h264dec_so
PRODUCT_PACKAGES += qin_vendor_lib_libstagefright_sprd_h264enc_so
PRODUCT_PACKAGES += qin_vendor_lib_libstagefright_sprd_h265dec_so
PRODUCT_PACKAGES += qin_vendor_lib_libstagefright_sprd_h265enc_so
PRODUCT_PACKAGES += qin_vendor_lib_libstagefright_sprd_mp3dec_so
PRODUCT_PACKAGES += qin_vendor_lib_libstagefright_sprd_mp3enc_so
PRODUCT_PACKAGES += qin_vendor_lib_libstagefright_sprd_mpeg4dec_so
PRODUCT_PACKAGES += qin_vendor_lib_libstagefright_sprd_mpeg4enc_so
PRODUCT_PACKAGES += qin_vendor_lib_libstagefright_sprd_vp9dec_so
PRODUCT_PACKAGES += qin_vendor_lib_libstagefright_sprd_vpxdec_so
PRODUCT_PACKAGES += qin_vendor_lib_libstagefrighthw_so
PRODUCT_PACKAGES += qin_vendor_lib_libsupl_so
PRODUCT_PACKAGES += qin_vendor_lib_libsutu_display_so
PRODUCT_PACKAGES += qin_vendor_lib_libteeproduction_so
PRODUCT_PACKAGES += qin_vendor_lib_libtinyalsa_utils_so
PRODUCT_PACKAGES += qin_vendor_lib_libtqvalidate_so
PRODUCT_PACKAGES += qin_vendor_lib_libtracedump_so
PRODUCT_PACKAGES += qin_vendor_lib_libusc_so
PRODUCT_PACKAGES += qin_vendor_lib_libvbeffect_so
PRODUCT_PACKAGES += qin_vendor_lib_libvbpga_so
PRODUCT_PACKAGES += qin_vendor_lib_libwebrtc_audio_preprocessing_so
PRODUCT_PACKAGES += qin_vendor_lib_libwvhidl_so
PRODUCT_PACKAGES += qin_vendor_lib_libyuv420_scaler_so
PRODUCT_PACKAGES += qin_vendor_lib_npidevice_PQTune_sp9863a_so
PRODUCT_PACKAGES += qin_vendor_lib_npidevice_autotestfinger_so
PRODUCT_PACKAGES += qin_vendor_lib_npidevice_autotestfm_so
PRODUCT_PACKAGES += qin_vendor_lib_npidevice_autotestgps_so
PRODUCT_PACKAGES += qin_vendor_lib_npidevice_autotestsensorinfo_so
PRODUCT_PACKAGES += qin_vendor_lib_npidevice_autotestsim_so
PRODUCT_PACKAGES += qin_vendor_lib_npidevice_autotesttcard_so
PRODUCT_PACKAGES += qin_vendor_lib_npidevice_autotestwifi_so
PRODUCT_PACKAGES += qin_vendor_lib_npidevice_libFactoryRadioTest_so
PRODUCT_PACKAGES += qin_vendor_lib_npidevice_libapdeepsleep_so
PRODUCT_PACKAGES += qin_vendor_lib_npidevice_libbt_sprd_eut_so
PRODUCT_PACKAGES += qin_vendor_lib_npidevice_libcharge_so
PRODUCT_PACKAGES += qin_vendor_lib_npidevice_libcheckkeybox_so
PRODUCT_PACKAGES += qin_vendor_lib_npidevice_libdloader_so
PRODUCT_PACKAGES += qin_vendor_lib_npidevice_libfm_sprd_eut_so
PRODUCT_PACKAGES += qin_vendor_lib_npidevice_libgetuid_so
PRODUCT_PACKAGES += qin_vendor_lib_npidevice_libgpio_so
PRODUCT_PACKAGES += qin_vendor_lib_npidevice_libgpspc_so
PRODUCT_PACKAGES += qin_vendor_lib_npidevice_libkeypadnpi_so
PRODUCT_PACKAGES += qin_vendor_lib_npidevice_liblcdnpi_so
PRODUCT_PACKAGES += qin_vendor_lib_npidevice_liblkvnpi_so
PRODUCT_PACKAGES += qin_vendor_lib_npidevice_libreadfixednv_so
PRODUCT_PACKAGES += qin_vendor_lib_npidevice_libtsxrawdata_so
PRODUCT_PACKAGES += qin_vendor_lib_npidevice_libwifieut_so
PRODUCT_PACKAGES += qin_vendor_lib_npidevice_nativemmifinger_so
PRODUCT_PACKAGES += qin_vendor_lib_power_sprd_so
PRODUCT_PACKAGES += qin_vendor_lib_production_libpubefuseapi_so
PRODUCT_PACKAGES += qin_vendor_lib_vendor_sprd_hardware_aprd_1_0_so
PRODUCT_PACKAGES += qin_vendor_lib_vendor_sprd_hardware_connmgr_1_0_so
PRODUCT_PACKAGES += qin_vendor_lib_vendor_sprd_hardware_enhance_1_0_so
PRODUCT_PACKAGES += qin_vendor_lib_vendor_sprd_hardware_gnss_2_0_so
PRODUCT_PACKAGES += qin_vendor_lib_vendor_sprd_hardware_log_1_0_so
PRODUCT_PACKAGES += qin_vendor_lib_vendor_sprd_hardware_power_3_0_so
PRODUCT_PACKAGES += qin_vendor_lib_vendor_sprd_hardware_radio_1_0_so
PRODUCT_PACKAGES += qin_vendor_lib_vendor_sprd_hardware_radio_flavor_1_0_so
PRODUCT_PACKAGES += qin_vendor_lib_vendor_sprd_hardware_thermal_1_0_so
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/product/build.prop:system/product/build.prop
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/bin/gatordstart:system/vendor/bin/gatordstart
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/bin/power/backlight/readme:system/vendor/bin/power/backlight/readme
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/bin/power/cpu/dvfs/readme:system/vendor/bin/power/cpu/dvfs/readme
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/bin/power/cpu/fix_freq/readme:system/vendor/bin/power/cpu/fix_freq/readme
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/bin/power/cpu/hotplug/readme:system/vendor/bin/power/cpu/hotplug/readme
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/bin/power/cpu/lit_freq/readme:system/vendor/bin/power/cpu/lit_freq/readme
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/bin/power/cpu/loading/readme:system/vendor/bin/power/cpu/loading/readme
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/bin/power/cpu/trans_table/readme:system/vendor/bin/power/cpu/trans_table/readme
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/bin/power/ddr/bm/readme:system/vendor/bin/power/ddr/bm/readme
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/bin/power/ddr/bm/tool/log_to_csv.sh:system/vendor/bin/power/ddr/bm/tool/log_to_csv.sh
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/bin/power/ddr/bm/tool/sharkl3_cm4_disable_smart_light.bin:system/vendor/bin/power/ddr/bm/tool/sharkl3_cm4_disable_smart_light.bin
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/bin/power/ddr/fix_freq/readme:system/vendor/bin/power/ddr/fix_freq/readme
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/bin/power/ddr/loading/readme:system/vendor/bin/power/ddr/loading/readme
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/bin/power/ddr/trans_table/readme:system/vendor/bin/power/ddr/trans_table/readme
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/bin/power/frame/readme:system/vendor/bin/power/frame/readme
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/bin/power/gpu/fix_freq/readme:system/vendor/bin/power/gpu/fix_freq/readme
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/bin/power/gpu/loading/readme:system/vendor/bin/power/gpu/loading/readme
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/bin/power/gpu/trans_table/readme:system/vendor/bin/power/gpu/trans_table/readme
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/bin/power/interrupt/readme:system/vendor/bin/power/interrupt/readme
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/bin/power/loadings/readme:system/vendor/bin/power/loadings/readme
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/bin/power/loadings/tool/loading.sh:system/vendor/bin/power/loadings/tool/loading.sh
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/bin/power/paras/readme:system/vendor/bin/power/paras/readme
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/bin/power/paras/tool/para.sh:system/vendor/bin/power/paras/tool/para.sh
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/bin/power/tops/readme:system/vendor/bin/power/tops/readme
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/bin/power/total/readme:system/vendor/bin/power/total/readme
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/bin/power/total/tool/total.sh:system/vendor/bin/power/total/tool/total.sh
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/bin/pvrhtbd:system/vendor/bin/pvrhtbd
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/bin/pvrhwperf:system/vendor/bin/pvrhwperf
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/bin/pvrlogdump:system/vendor/bin/pvrlogdump
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/bin/pvrlogsplit:system/vendor/bin/pvrlogsplit
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/default.prop:system/vendor/default.prop
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/etc/BBAT.conf:system/vendor/etc/BBAT.conf
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/etc/PCBA.conf:system/vendor/etc/PCBA.conf
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/etc/a2dp_audio_policy_configuration.xml:system/vendor/etc/a2dp_audio_policy_configuration.xml
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/etc/adb.iso:system/vendor/etc/adb.iso
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/etc/audio_effects.conf:system/vendor/etc/audio_effects.conf
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/etc/audio_effects.xml:system/vendor/etc/audio_effects.xml
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/etc/audio_hw.xml:system/vendor/etc/audio_hw.xml
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/etc/audio_para:system/vendor/etc/audio_para
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/etc/audio_policy_configuration.xml:system/vendor/etc/audio_policy_configuration.xml
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/etc/audio_policy_configuration_smart_pa.xml:system/vendor/etc/audio_policy_configuration_smart_pa.xml
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/etc/audio_policy_volumes.xml:system/vendor/etc/audio_policy_volumes.xml
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/etc/codec_pga.xml:system/vendor/etc/codec_pga.xml
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/etc/config.xml:system/vendor/etc/config.xml
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/etc/connectivity_calibration.ini:system/vendor/etc/connectivity_calibration.ini \
    vendor/qin/qin2pro/proprietary/vendor/etc/connectivity_calibration.ini:system/etc/connectivity_calibration.ini
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/etc/connectivity_configure.ini:system/vendor/etc/connectivity_configure.ini \
    vendor/qin/qin2pro/proprietary/vendor/etc/connectivity_configure.ini:system/etc/connectivity_configure.ini
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/etc/default_volume_tables.xml:system/vendor/etc/default_volume_tables.xml
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/etc/enhance/abc.xml:system/vendor/etc/enhance/abc.xml
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/etc/enhance/bld.xml:system/vendor/etc/enhance/bld.xml
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/etc/enhance/cms.xml:system/vendor/etc/enhance/cms.xml
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/etc/enhance/gamma.xml:system/vendor/etc/enhance/gamma.xml
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/etc/fs_config_dirs:system/vendor/etc/fs_config_dirs
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/etc/fs_config_files:system/vendor/etc/fs_config_files
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/etc/fstab.enableswap:system/vendor/etc/fstab.enableswap
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/etc/fstab.s9863a1h10:system/vendor/etc/fstab.s9863a1h10
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/etc/init/android.hardware.audio@2.0-service.rc:system/vendor/etc/init/android.hardware.audio@2.0-service.rc
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/etc/init/android.hardware.bluetooth.a2dp@1.0-service.rc:system/vendor/etc/init/android.hardware.bluetooth.a2dp@1.0-service.rc
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/etc/init/android.hardware.bluetooth@1.0-service.unisoc.rc:system/vendor/etc/init/android.hardware.bluetooth@1.0-service.unisoc.rc
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/etc/init/android.hardware.drm@1.1-service.clearkey.rc:system/vendor/etc/init/android.hardware.drm@1.1-service.clearkey.rc
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/etc/init/android.hardware.usb@1.1-service.rc:system/vendor/etc/init/android.hardware.usb@1.1-service.rc
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/etc/init/autotest.rc:system/vendor/etc/init/autotest.rc
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/etc/init/charge.rc:system/vendor/etc/init/charge.rc
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/etc/init/cp_diskserver.rc:system/vendor/etc/init/cp_diskserver.rc
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/etc/init/engpc.rc:system/vendor/etc/init/engpc.rc
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/etc/init/ext_data.rc:system/vendor/etc/init/ext_data.rc
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/etc/init/factorytest.rc:system/vendor/etc/init/factorytest.rc
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/etc/init/disable_fbcdc.rc:system/vendor/etc/init/disable_fbcdc.rc
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/etc/init/hw/init.common.rc:system/vendor/etc/init/hw/init.common.rc
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/etc/init/hw/init.ram.rc:system/vendor/etc/init/hw/init.ram.rc
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/etc/init/hw/init.s9863a1h10.rc:system/vendor/etc/init/hw/init.s9863a1h10.rc
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/etc/init/hw/init.s9863a1h10.usb.rc:system/vendor/etc/init/hw/init.s9863a1h10.usb.rc
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/etc/init/hw/init.storage.rc:system/vendor/etc/init/hw/init.storage.rc
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/etc/init/init.leddrv.rc:system/vendor/etc/init/init.leddrv.rc
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/etc/init/init.vibdrv.rc:system/vendor/etc/init/init.vibdrv.rc
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/etc/init/init_expand.rc:system/vendor/etc/init/init_expand.rc
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/etc/init/iqfeed.rc:system/vendor/etc/init/iqfeed.rc
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/etc/init/mlogservice.rc:system/vendor/etc/init/mlogservice.rc
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/etc/init/modem_control.rc:system/vendor/etc/init/modem_control.rc
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/etc/init/modemd.rc:system/vendor/etc/init/modemd.rc
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/etc/init/otpd.rc:system/vendor/etc/init/otpd.rc
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/etc/init/phasecheckserver.rc:system/vendor/etc/init/phasecheckserver.rc
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/etc/init/refnotify.rc:system/vendor/etc/init/refnotify.rc
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/etc/init/slogmodem.rc:system/vendor/etc/init/slogmodem.rc
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/etc/init/srtd.rc:system/vendor/etc/init/srtd.rc
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/etc/init/thermald.rc:system/vendor/etc/init/thermald.rc
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/etc/init/tsupplicant.rc:system/vendor/etc/init/tsupplicant.rc
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/etc/init/vendor.sprd.hardware.aprd@1.0-service.rc:system/vendor/etc/init/vendor.sprd.hardware.aprd@1.0-service.rc
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/etc/init/vendor.sprd.hardware.connmgr@1.0-service.rc:system/vendor/etc/init/vendor.sprd.hardware.connmgr@1.0-service.rc
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/etc/init/vendor.sprd.hardware.enhance@1.0-service.rc:system/vendor/etc/init/vendor.sprd.hardware.enhance@1.0-service.rc
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/etc/init/vendor.sprd.hardware.face@1.0-service.rc:system/vendor/etc/init/vendor.sprd.hardware.face@1.0-service.rc
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/etc/init/vendor.sprd.hardware.gnss@2.0-service.rc:system/vendor/etc/init/vendor.sprd.hardware.gnss@2.0-service.rc
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/etc/init/vendor.sprd.hardware.log@1.0-service.rc:system/vendor/etc/init/vendor.sprd.hardware.log@1.0-service.rc
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/etc/init/vendor.sprd.hardware.power@3.0-service.rc:system/vendor/etc/init/vendor.sprd.hardware.power@3.0-service.rc
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/etc/init/vendor.sprd.hardware.thermal@1.0-service.rc:system/vendor/etc/init/vendor.sprd.hardware.thermal@1.0-service.rc
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/etc/init/wcn.rc:system/vendor/etc/init/wcn.rc
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/etc/init/wcnd.rc:system/vendor/etc/init/wcnd.rc
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/etc/init/ylog_lite.rc:system/vendor/etc/init/ylog_lite.rc
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/etc/media_codecs.xml:system/vendor/etc/media_codecs.xml
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/etc/media_codecs_google_audio.xml:system/vendor/etc/media_codecs_google_audio.xml
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/etc/media_codecs_google_telephony.xml:system/vendor/etc/media_codecs_google_telephony.xml
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/etc/media_codecs_google_video.xml:system/vendor/etc/media_codecs_google_video.xml
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/etc/media_codecs_performance.xml:system/vendor/etc/media_codecs_performance.xml
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/etc/media_profiles_V1_0.xml:system/vendor/etc/media_profiles_V1_0.xml
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/etc/media_profiles_turnkey.xml:system/vendor/etc/media_profiles_turnkey.xml
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/etc/mlogservice.conf:system/vendor/etc/mlogservice.conf
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/etc/numeric_operator.xml:system/vendor/etc/numeric_operator.xml
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/etc/permissions/android.hardware.bluetooth_le.xml:system/vendor/etc/permissions/android.hardware.bluetooth_le.xml
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/etc/permissions/android.hardware.camera.flash-autofocus.xml:system/vendor/etc/permissions/android.hardware.camera.flash-autofocus.xml
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/etc/permissions/android.hardware.camera.front.xml:system/vendor/etc/permissions/android.hardware.camera.front.xml
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/etc/permissions/android.hardware.consumerir.xml:system/vendor/etc/permissions/android.hardware.consumerir.xml
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/etc/permissions/android.hardware.location.gps.xml:system/vendor/etc/permissions/android.hardware.location.gps.xml
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/etc/permissions/android.hardware.opengles.aep.xml:system/vendor/etc/permissions/android.hardware.opengles.aep.xml
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/etc/permissions/android.hardware.telephony.gsm.xml:system/vendor/etc/permissions/android.hardware.telephony.gsm.xml
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/etc/permissions/android.hardware.touchscreen.multitouch.distinct.xml:system/vendor/etc/permissions/android.hardware.touchscreen.multitouch.distinct.xml
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/etc/permissions/android.hardware.touchscreen.xml:system/vendor/etc/permissions/android.hardware.touchscreen.xml
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/etc/permissions/android.hardware.usb.accessory.xml:system/vendor/etc/permissions/android.hardware.usb.accessory.xml
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/etc/permissions/android.hardware.usb.host.xml:system/vendor/etc/permissions/android.hardware.usb.host.xml
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/etc/permissions/android.hardware.wifi.direct.xml:system/vendor/etc/permissions/android.hardware.wifi.direct.xml
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/etc/permissions/android.hardware.wifi.xml:system/vendor/etc/permissions/android.hardware.wifi.xml
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/etc/permissions/android.software.cts.xml:system/vendor/etc/permissions/android.software.cts.xml
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/etc/permissions/android.software.midi.xml:system/vendor/etc/permissions/android.software.midi.xml
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/etc/permissions/android.software.verified_boot.xml:system/vendor/etc/permissions/android.software.verified_boot.xml
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/etc/permissions/handheld_core_hardware.xml:system/vendor/etc/permissions/handheld_core_hardware.xml
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/etc/permissions/vendor.sprd.hardware.faceid.xml:system/vendor/etc/permissions/vendor.sprd.hardware.faceid.xml
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/etc/power_resource_file_info.xml:system/vendor/etc/power_resource_file_info.xml
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/etc/power_scene_config.xml:system/vendor/etc/power_scene_config.xml
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/etc/power_scene_id_define.txt:system/vendor/etc/power_scene_id_define.txt
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/etc/primary_audio_policy_configuration.xml:system/vendor/etc/primary_audio_policy_configuration.xml
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/etc/primary_audio_policy_configuration_smart_pa.xml:system/vendor/etc/primary_audio_policy_configuration_smart_pa.xml
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/etc/public.libraries.txt:system/vendor/etc/public.libraries.txt
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/etc/r_submix_audio_policy_configuration.xml:system/vendor/etc/r_submix_audio_policy_configuration.xml
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/etc/record_tone_1.pcm:system/vendor/etc/record_tone_1.pcm
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/etc/record_tone_2.pcm:system/vendor/etc/record_tone_2.pcm
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/etc/res/images/colon_1080X1920.png:system/vendor/etc/res/images/colon_1080X1920.png
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/etc/res/images/colon_1440X2560.png:system/vendor/etc/res/images/colon_1440X2560.png
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/etc/res/images/colon_360X640.png:system/vendor/etc/res/images/colon_360X640.png
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/etc/res/images/colon_480X800.png:system/vendor/etc/res/images/colon_480X800.png
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/etc/res/images/colon_720X1280.png:system/vendor/etc/res/images/colon_720X1280.png
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/etc/res/images/error_1_1080X1920.png:system/vendor/etc/res/images/error_1_1080X1920.png
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/etc/res/images/error_1_1440X2560.png:system/vendor/etc/res/images/error_1_1440X2560.png
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/etc/res/images/error_1_360X640.png:system/vendor/etc/res/images/error_1_360X640.png
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/etc/res/images/error_1_480X800.png:system/vendor/etc/res/images/error_1_480X800.png
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/etc/res/images/error_1_720X1280.png:system/vendor/etc/res/images/error_1_720X1280.png
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/etc/res/images/error_2_1080X1920.png:system/vendor/etc/res/images/error_2_1080X1920.png
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/etc/res/images/error_2_1440X2560.png:system/vendor/etc/res/images/error_2_1440X2560.png
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/etc/res/images/error_2_360X640.png:system/vendor/etc/res/images/error_2_360X640.png
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/etc/res/images/error_2_480X800.png:system/vendor/etc/res/images/error_2_480X800.png
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/etc/res/images/error_2_720X1280.png:system/vendor/etc/res/images/error_2_720X1280.png
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/etc/res/images/error_3_1080X1920.png:system/vendor/etc/res/images/error_3_1080X1920.png
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/etc/res/images/error_3_1440X2560.png:system/vendor/etc/res/images/error_3_1440X2560.png
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/etc/res/images/error_3_360X640.png:system/vendor/etc/res/images/error_3_360X640.png
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/etc/res/images/error_3_480X800.png:system/vendor/etc/res/images/error_3_480X800.png
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/etc/res/images/error_3_720X1280.png:system/vendor/etc/res/images/error_3_720X1280.png
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/etc/res/images/indeterminate0.png:system/vendor/etc/res/images/indeterminate0.png
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/etc/res/images/indeterminate0_1080X1920.png:system/vendor/etc/res/images/indeterminate0_1080X1920.png
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/etc/res/images/indeterminate0_1440X2560.png:system/vendor/etc/res/images/indeterminate0_1440X2560.png
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/etc/res/images/indeterminate0_360X640.png:system/vendor/etc/res/images/indeterminate0_360X640.png
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/etc/res/images/indeterminate0_480X800.png:system/vendor/etc/res/images/indeterminate0_480X800.png
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/etc/res/images/indeterminate0_720X1280.png:system/vendor/etc/res/images/indeterminate0_720X1280.png
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/etc/res/images/indeterminate1.png:system/vendor/etc/res/images/indeterminate1.png
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/etc/res/images/indeterminate1_1080X1920.png:system/vendor/etc/res/images/indeterminate1_1080X1920.png
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/etc/res/images/indeterminate1_1440X2560.png:system/vendor/etc/res/images/indeterminate1_1440X2560.png
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/etc/res/images/indeterminate1_360X640.png:system/vendor/etc/res/images/indeterminate1_360X640.png
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/etc/res/images/indeterminate1_480X800.png:system/vendor/etc/res/images/indeterminate1_480X800.png
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/etc/res/images/indeterminate1_720X1280.png:system/vendor/etc/res/images/indeterminate1_720X1280.png
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/etc/res/images/indeterminate2.png:system/vendor/etc/res/images/indeterminate2.png
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/etc/res/images/indeterminate2_1080X1920.png:system/vendor/etc/res/images/indeterminate2_1080X1920.png
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/etc/res/images/indeterminate2_1440X2560.png:system/vendor/etc/res/images/indeterminate2_1440X2560.png
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/etc/res/images/indeterminate2_360X640.png:system/vendor/etc/res/images/indeterminate2_360X640.png
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/etc/res/images/indeterminate2_480X800.png:system/vendor/etc/res/images/indeterminate2_480X800.png
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/etc/res/images/indeterminate2_720X1280.png:system/vendor/etc/res/images/indeterminate2_720X1280.png
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/etc/res/images/indeterminate3.png:system/vendor/etc/res/images/indeterminate3.png
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/etc/res/images/indeterminate3_1080X1920.png:system/vendor/etc/res/images/indeterminate3_1080X1920.png
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/etc/res/images/indeterminate3_1440X2560.png:system/vendor/etc/res/images/indeterminate3_1440X2560.png
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/etc/res/images/indeterminate3_360X640.png:system/vendor/etc/res/images/indeterminate3_360X640.png
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/etc/res/images/indeterminate3_480X800.png:system/vendor/etc/res/images/indeterminate3_480X800.png
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/etc/res/images/indeterminate3_720X1280.png:system/vendor/etc/res/images/indeterminate3_720X1280.png
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/etc/res/images/indeterminate4.png:system/vendor/etc/res/images/indeterminate4.png
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/etc/res/images/indeterminate4_1080X1920.png:system/vendor/etc/res/images/indeterminate4_1080X1920.png
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/etc/res/images/indeterminate4_1440X2560.png:system/vendor/etc/res/images/indeterminate4_1440X2560.png
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/etc/res/images/indeterminate4_360X640.png:system/vendor/etc/res/images/indeterminate4_360X640.png
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/etc/res/images/indeterminate4_480X800.png:system/vendor/etc/res/images/indeterminate4_480X800.png
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/etc/res/images/indeterminate4_720X1280.png:system/vendor/etc/res/images/indeterminate4_720X1280.png
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/etc/res/images/indeterminate5.png:system/vendor/etc/res/images/indeterminate5.png
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/etc/res/images/indeterminate5_1080X1920.png:system/vendor/etc/res/images/indeterminate5_1080X1920.png
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/etc/res/images/indeterminate5_1440X2560.png:system/vendor/etc/res/images/indeterminate5_1440X2560.png
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/etc/res/images/indeterminate5_360X640.png:system/vendor/etc/res/images/indeterminate5_360X640.png
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/etc/res/images/indeterminate5_480X800.png:system/vendor/etc/res/images/indeterminate5_480X800.png
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/etc/res/images/indeterminate5_720X1280.png:system/vendor/etc/res/images/indeterminate5_720X1280.png
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/etc/res/images/indeterminate6.png:system/vendor/etc/res/images/indeterminate6.png
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/etc/res/images/indeterminate6_1080X1920.png:system/vendor/etc/res/images/indeterminate6_1080X1920.png
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/etc/res/images/indeterminate6_1440X2560.png:system/vendor/etc/res/images/indeterminate6_1440X2560.png
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/etc/res/images/indeterminate6_360X640.png:system/vendor/etc/res/images/indeterminate6_360X640.png
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/etc/res/images/indeterminate6_480X800.png:system/vendor/etc/res/images/indeterminate6_480X800.png
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/etc/res/images/indeterminate6_720X1280.png:system/vendor/etc/res/images/indeterminate6_720X1280.png
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/etc/res/images/number_0_1080X1920.png:system/vendor/etc/res/images/number_0_1080X1920.png
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/etc/res/images/number_0_1440X2560.png:system/vendor/etc/res/images/number_0_1440X2560.png
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/etc/res/images/number_0_360X640.png:system/vendor/etc/res/images/number_0_360X640.png
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/etc/res/images/number_0_480X800.png:system/vendor/etc/res/images/number_0_480X800.png
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/etc/res/images/number_0_720X1280.png:system/vendor/etc/res/images/number_0_720X1280.png
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/etc/res/images/number_1_1080X1920.png:system/vendor/etc/res/images/number_1_1080X1920.png
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/etc/res/images/number_1_1440X2560.png:system/vendor/etc/res/images/number_1_1440X2560.png
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/etc/res/images/number_1_360X640.png:system/vendor/etc/res/images/number_1_360X640.png
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/etc/res/images/number_1_480X800.png:system/vendor/etc/res/images/number_1_480X800.png
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/etc/res/images/number_1_720X1280.png:system/vendor/etc/res/images/number_1_720X1280.png
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/etc/res/images/number_2_1080X1920.png:system/vendor/etc/res/images/number_2_1080X1920.png
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/etc/res/images/number_2_1440X2560.png:system/vendor/etc/res/images/number_2_1440X2560.png
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/etc/res/images/number_2_480X800.png:system/vendor/etc/res/images/number_2_480X800.png
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/etc/res/images/number_2_720X1280.png:system/vendor/etc/res/images/number_2_720X1280.png
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/etc/res/images/number_3_1080X1920.png:system/vendor/etc/res/images/number_3_1080X1920.png
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/etc/res/images/number_3_1440X2560.png:system/vendor/etc/res/images/number_3_1440X2560.png
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/etc/res/images/number_3_360X640.png:system/vendor/etc/res/images/number_3_360X640.png
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/etc/res/images/number_3_480X800.png:system/vendor/etc/res/images/number_3_480X800.png
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/etc/res/images/number_3_720X1280.png:system/vendor/etc/res/images/number_3_720X1280.png
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/etc/res/images/number_4_1080X1920.png:system/vendor/etc/res/images/number_4_1080X1920.png
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/etc/res/images/number_4_1440X2560.png:system/vendor/etc/res/images/number_4_1440X2560.png
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/etc/res/images/number_4_360X640.png:system/vendor/etc/res/images/number_4_360X640.png
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/etc/res/images/number_4_480X800.png:system/vendor/etc/res/images/number_4_480X800.png
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/etc/res/images/number_4_720X1280.png:system/vendor/etc/res/images/number_4_720X1280.png
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/etc/res/images/number_5_1080X1920.png:system/vendor/etc/res/images/number_5_1080X1920.png
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/etc/res/images/number_5_1440X2560.png:system/vendor/etc/res/images/number_5_1440X2560.png
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/etc/res/images/number_5_360X640.png:system/vendor/etc/res/images/number_5_360X640.png
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/etc/res/images/number_5_480X800.png:system/vendor/etc/res/images/number_5_480X800.png
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/etc/res/images/number_5_720X1280.png:system/vendor/etc/res/images/number_5_720X1280.png
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/etc/res/images/number_6_1080X1920.png:system/vendor/etc/res/images/number_6_1080X1920.png
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/etc/res/images/number_6_1440X2560.png:system/vendor/etc/res/images/number_6_1440X2560.png
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/etc/res/images/number_6_360X640.png:system/vendor/etc/res/images/number_6_360X640.png
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/etc/res/images/number_6_480X800.png:system/vendor/etc/res/images/number_6_480X800.png
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/etc/res/images/number_6_720X1280.png:system/vendor/etc/res/images/number_6_720X1280.png
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/etc/res/images/number_7_1080X1920.png:system/vendor/etc/res/images/number_7_1080X1920.png
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/etc/res/images/number_7_1440X2560.png:system/vendor/etc/res/images/number_7_1440X2560.png
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/etc/res/images/number_7_360X640.png:system/vendor/etc/res/images/number_7_360X640.png
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/etc/res/images/number_7_480X800.png:system/vendor/etc/res/images/number_7_480X800.png
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/etc/res/images/number_7_720X1280.png:system/vendor/etc/res/images/number_7_720X1280.png
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/etc/res/images/number_8_1080X1920.png:system/vendor/etc/res/images/number_8_1080X1920.png
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/etc/res/images/number_8_1440X2560.png:system/vendor/etc/res/images/number_8_1440X2560.png
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/etc/res/images/number_8_360X640.png:system/vendor/etc/res/images/number_8_360X640.png
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/etc/res/images/number_8_480X800.png:system/vendor/etc/res/images/number_8_480X800.png
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/etc/res/images/number_8_720X1280.png:system/vendor/etc/res/images/number_8_720X1280.png
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/etc/res/images/number_9_1080X1920.png:system/vendor/etc/res/images/number_9_1080X1920.png
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/etc/res/images/number_9_1440X2560.png:system/vendor/etc/res/images/number_9_1440X2560.png
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/etc/res/images/number_9_360X640.png:system/vendor/etc/res/images/number_9_360X640.png
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/etc/res/images/number_9_480X800.png:system/vendor/etc/res/images/number_9_480X800.png
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/etc/res/images/number_9_720X1280.png:system/vendor/etc/res/images/number_9_720X1280.png
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/etc/res/images/number_percent_1080X1920.png:system/vendor/etc/res/images/number_percent_1080X1920.png
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/etc/res/images/number_percent_1440X2560.png:system/vendor/etc/res/images/number_percent_1440X2560.png
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/etc/res/images/number_percent_360X640.png:system/vendor/etc/res/images/number_percent_360X640.png
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/etc/res/images/number_percent_480X800.png:system/vendor/etc/res/images/number_percent_480X800.png
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/etc/res/images/number_percent_720X1280.png:system/vendor/etc/res/images/number_percent_720X1280.png
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/etc/rx_data.pcm:system/vendor/etc/rx_data.pcm
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/etc/seccomp_policy/mediaextractor.policy:system/vendor/etc/seccomp_policy/mediaextractor.policy
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/etc/selinux/precompiled_sepolicy.plat_and_mapping.sha256:system/vendor/etc/selinux/precompiled_sepolicy.plat_and_mapping.sha256
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/etc/slog_modem.conf:system/vendor/etc/slog_modem.conf
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/etc/slog_modem_autotest.conf:system/vendor/etc/slog_modem_autotest.conf
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/etc/slog_modem_cali.conf:system/vendor/etc/slog_modem_cali.conf
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/etc/slog_modem_factory.conf:system/vendor/etc/slog_modem_factory.conf
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/etc/smart_amp_init.bin:system/vendor/etc/smart_amp_init.bin
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/etc/spirentroot.cer:system/vendor/etc/spirentroot.cer
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/etc/supl.xml:system/vendor/etc/supl.xml
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/etc/thermal.conf:system/vendor/etc/thermal.conf
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/etc/tiny_hw.xml:system/vendor/etc/tiny_hw.xml
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/etc/usb_audio_policy_configuration.xml:system/vendor/etc/usb_audio_policy_configuration.xml
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/lib/modules/sprdwl_ng.ko:system/vendor/lib/modules/sprdwl_ng.ko \
    vendor/qin/qin2pro/proprietary/vendor/lib/modules/sprdbt_tty.ko:system/vendor/lib/modules/sprdbt_tty.ko \
    vendor/qin/qin2pro/proprietary/vendor/lib/modules/sprd_fm.ko:system/vendor/lib/modules/sprd_fm.ko \
    vendor/qin/qin2pro/proprietary/vendor/lib/modules/pvrsrvkm.ko:system/vendor/lib/modules/pvrsrvkm.ko
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/etc/wifi/wpa_supplicant.conf:system/vendor/etc/wifi/wpa_supplicant.conf \
    vendor/qin/qin2pro/proprietary/vendor/etc/wifi/p2p_supplicant.conf:system/vendor/etc/wifi/p2p_supplicant.conf
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/firmware/EXEC_CALIBRATE_MAG_IMAGE:system/vendor/firmware/EXEC_CALIBRATE_MAG_IMAGE
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/firmware/faceid.elf:system/vendor/firmware/faceid.elf
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/firmware/focaltech-FT5x46.bin:system/vendor/firmware/focaltech-FT5x46.bin
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/firmware/mafp.elf:system/vendor/firmware/mafp.elf
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/firmware/rgx.fw.signed.22.86.104.218:system/vendor/firmware/rgx.fw.signed.22.86.104.218
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/media/audio_sample.pcm:system/vendor/media/audio_sample.pcm
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/ueventd.rc:system/vendor/etc/ueventd.rc
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/usr/idc/adaptive_ts.idc:system/vendor/usr/idc/adaptive_ts.idc
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/usr/keylayout/adaptive_ts.kl:system/vendor/usr/keylayout/adaptive_ts.kl
PRODUCT_COPY_FILES += \
    vendor/qin/qin2pro/proprietary/vendor/usr/keylayout/gpio-keys.kl:system/vendor/usr/keylayout/gpio-keys.kl

# stock audio HAL impls (32-bit patched: updateSink/SourceMetadata no-op)
PRODUCT_PACKAGES += qin_audio4_impl_override qin_audio_effect4_impl_override
# Qin2Pro WIP: AOSP-built compatibility libs (32-bit OMX/RIL + audio/keymaster deps)
PRODUCT_PACKAGES += qin_vendor_lib_libminijail_so
# SPRD wifi HAL blob renamed -impl; libwifi-hal-sprd.so is now a NULL-guard
# shim (device/qin/qin2pro/wifihal_shim) that dlopens this blob.
PRODUCT_COPY_FILES +=     vendor/qin/qin2pro/proprietary/vendor/lib64/libwifi-hal-sprd.so:system/vendor/lib64/libwifi-hal-sprd-impl.so
PRODUCT_PACKAGES += libwifi-hal-sprd
PRODUCT_COPY_FILES +=     vendor/qin/qin2pro/proprietary/vendor/lib/libwifi-hal-sprd.so:system/vendor/lib/libwifi-hal-sprd.so
PRODUCT_COPY_FILES +=     vendor/qin/qin2pro/proprietary/vendor/etc/wifi/vendor_hals/sprd.xml:system/vendor/etc/wifi/vendor_hals/sprd.xml

PRODUCT_PACKAGES += qin_stock_libhwc2on1adapter

PRODUCT_PACKAGES += qin_stock_libhwc2onfbadapter

PRODUCT_COPY_FILES += vendor/qin/qin2pro/proprietary/vendor/lib/android.hardware.soundtrigger@2.0.so:system/vendor/lib/android.hardware.soundtrigger@2.0.so


PRODUCT_PACKAGES += qin_stock_graphics_mapper_2_0_impl

PRODUCT_PACKAGES += qin_stock_graphics_allocator_2_0_impl

PRODUCT_PACKAGES += qin_stock_ir_1_0_impl

PRODUCT_PACKAGES += qin_stock_consumerir_default

# vendor-lib closure shims (stock blobs + unversioned protobuf name)
PRODUCT_PACKAGES += \
    qin_vendor_lib64_android_hardware_radio_deprecated_1_0_so \
    qin_vendor_lib_android_hardware_radio_deprecated_1_0_so \
    qin_vendor_lib64_libsensorndkbridge_so \
    qin_vendor_lib_libsensorndkbridge_so \
    qin_vendor_lib64_libprotobuf_cpp_lite_shim_so \
    qin_vendor_lib_libprotobuf_cpp_lite_shim_so

# vndk libs the apex dropped; vendor/lib64 direct-path copies
PRODUCT_PACKAGES += \
    qin_vlib64_android_hardware_audio_common_2_0 \
    qin_vlib_android_hardware_audio_common_2_0 \
    qin_vlib64_android_hardware_configstore_1_0 \
    qin_vlib_android_hardware_configstore_1_0 \
    qin_vlib64_android_hardware_configstore_1_1 \
    qin_vlib_android_hardware_configstore_1_1 \
    qin_vlib64_android_hardware_graphics_allocator_2_0 \
    qin_vlib_android_hardware_graphics_allocator_2_0 \
    qin_vlib64_android_hardware_media_omx_1_0 \
    qin_vlib_android_hardware_media_omx_1_0 \
    qin_vlib64_libaudioutils \
    qin_vlib_libaudioutils \
    qin_vlib64_libcamera_metadata \
    qin_vlib_libcamera_metadata \
    qin_vlib64_libcap \
    qin_vlib_libcap \
    qin_vlib64_libfmq \
    qin_vlib_libfmq \
    qin_vlib64_libhardware_legacy \
    qin_vlib_libhardware_legacy \
    qin_vlib64_libmedia_helper \
    qin_vlib_libmedia_helper \
    qin_vlib64_libnetutils \
    qin_vlib_libnetutils \
    qin_vlib64_libnl \
    qin_vlib_libnl \
    qin_vlib64_libpng \
    qin_vlib_libpng \
    qin_vlib64_libpower \
    qin_vlib_libpower \
    qin_vlib64_libsysutils \
    qin_vlib_libsysutils \
    qin_vlib64_libtinyalsa \
    qin_vlib_libtinyalsa \
    qin_vlib64_libtinyxml2 \
    qin_vlib_libtinyxml2 \
    qin_vlib64_libwifi_system_iface \
    qin_vlib_libwifi_system_iface \
    qin_vlib64_libyuv \
    qin_vlib_libyuv \
    qin_vlib64_libziparchive \
    qin_vlib_libziparchive

# second-order deps of copied vndk libs
PRODUCT_PACKAGES += \
    qin_vlib64_android_hardware_graphics_bufferqueue_1_0 \
    qin_vlib_android_hardware_graphics_bufferqueue_1_0 \
    qin_vlib64_android_hardware_media_1_0 \
    qin_vlib_android_hardware_media_1_0 \
    qin_vlib64_android_system_suspend_1_0 \
    qin_vlib_android_system_suspend_1_0 \
    qin_vlib64_libjpeg \
    qin_vlib_libjpeg \
    qin_vlib64_libspeexresampler \
    qin_vlib_libspeexresampler

# libui closure for sphal namespace
PRODUCT_PACKAGES += \
    qin_vlib64_libui \
    qin_vlib_libui \
    qin_vlib64_android_hardware_graphics_allocator_3_0 \
    qin_vlib_android_hardware_graphics_allocator_3_0 \
    qin_vlib64_android_hardware_graphics_allocator_4_0 \
    qin_vlib_android_hardware_graphics_allocator_4_0

# remaining camera closure impls (stock blobs)
PRODUCT_PACKAGES += \
    qin_vendor_lib64_camera_device_1_0_impl_so \
    qin_vendor_lib_camera_device_1_0_impl_so \
    qin_vendor_lib64_camera_device_3_4_external_impl_so \
    qin_vendor_lib_camera_device_3_4_external_impl_so
